// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrovaLibro.Context.DataModels;

public partial class TApiRestHeader
{
    public long Id { get; set; }

    public long IdApiRest { get; set; }

    public string CaKey { get; set; }

    public string CaValue { get; set; }

    public virtual TApiRest IdApiRestNavigation { get; set; }
}