// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrovaLibro.Context.DataModels;

public partial class TApiRest
{
    public long Id { get; set; }

    public string CaName { get; set; }

    public string CaUrl { get; set; }

    public virtual ICollection<TApiRestHeader> TApiRestHeaders { get; set; } = new List<TApiRestHeader>();
}