// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrovaLibro.DataModels;

public partial class TBook
{
    public long Id { get; set; }

    public long IdUser { get; set; }

    public string CaNameUser { get; set; }

    public string CaCityUser { get; set; }

    public long IdCategory { get; set; }

    public long IdCategorySub { get; set; }

    public long IdTarget { get; set; }

    public string CaTitle { get; set; }

    public string CaDescription { get; set; }

    public string CaAuthor { get; set; }

    public string CaPublisher { get; set; }

    public string CaIsbn { get; set; }

    public bool? FlNew { get; set; }

    public string CaCover { get; set; }

    public decimal? CdCoverPrice { get; set; }

    public decimal CdPrice { get; set; }

    public decimal CdShippingPrice { get; set; }

    public bool FlShipping { get; set; }

    public bool FlSelling { get; set; }

    public bool? FlActive { get; set; }

    public DateTime DtCreation { get; set; }

    public DateTime DtUpdate { get; set; }

    public virtual TCategory IdCategoryNavigation { get; set; }

    public virtual TCategorySub IdCategorySubNavigation { get; set; }

    public virtual TTarget IdTargetNavigation { get; set; }

    public virtual ICollection<TComunication> TComunications { get; set; } = new List<TComunication>();
}