// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrovaLibro.DataModels;

public partial class TCategorySub
{
    public long Id { get; set; }

    public long IdCategory { get; set; }

    public string CaName { get; set; }

    public string CaDescription { get; set; }

    public virtual TCategory IdCategoryNavigation { get; set; }

    public virtual ICollection<TBook> TBooks { get; set; } = new List<TBook>();
}