// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrovaLibro.DataModels;

public partial class TComunication
{
    public long Id { get; set; }

    public long IdBook { get; set; }

    public long IdUserSender { get; set; }

    public string CaMessage { get; set; }

    public bool FlRead { get; set; }

    public DateTime DtCreation { get; set; }

    public virtual TBook IdBookNavigation { get; set; }
}