// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrovaLibro.Context.DataModels;

public partial class TSysCountry
{
    public long Id { get; set; }

    public string CaCountryName { get; set; }

    public bool? FlActive { get; set; }

    public virtual ICollection<TSysProvince> TSysProvinces { get; set; } = new List<TSysProvince>();
}