// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrovaLibro.Context.DataModels;

public partial class TSysProvince
{
    public long Id { get; set; }

    public long IdCountry { get; set; }

    public string CaProvinceName { get; set; }

    public string CaProvinceCode { get; set; }

    public virtual TSysCountry IdCountryNavigation { get; set; }

    public virtual ICollection<TSysCity> TSysCities { get; set; } = new List<TSysCity>();
}