// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrovaLibro.Context.DataModels;

public partial class TSysCity
{
    public long Id { get; set; }

    public long IdProvince { get; set; }

    public string CaCityName { get; set; }

    public string CaCityCode { get; set; }

    public virtual TSysProvince IdProvinceNavigation { get; set; }
}