// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrovaLibro.Context.DataModels;

public partial class TSysUser
{
    public long Id { get; set; }

    public long IdCity { get; set; }

    public long IdProvince { get; set; }

    public string CaEmail { get; set; }

    public string CaPassword { get; set; }

    public string CaName { get; set; }

    public string CaSurname { get; set; }

    public string CaCell { get; set; }

    public string CaFiscalCode { get; set; }

    public string CaAddress { get; set; }

    public string CaCap { get; set; }

    public string CaIban { get; set; }

    public int CdRating { get; set; }

    public bool? FlShipping { get; set; }

    public bool? FlMarketing { get; set; }

    public DateTime? DaCreation { get; set; }

    public DateTime? DaLastActivity { get; set; }

    public string CaIpaddress { get; set; }

    public bool? FlOnline { get; set; }

    public bool? FlActive { get; set; }
}