// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using TrovaLibro.DataModels;

namespace TrovaLibro.DataContext;

public partial class DbTrovaLibroContext : DbContext
{
    public DbTrovaLibroContext(DbContextOptions<DbTrovaLibroContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TBook> TBooks { get; set; }

    public virtual DbSet<TCategory> TCategories { get; set; }

    public virtual DbSet<TCategorySub> TCategorySubs { get; set; }

    public virtual DbSet<TComunication> TComunications { get; set; }

    public virtual DbSet<TTarget> TTargets { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TBook>(entity =>
        {
            entity.ToTable("T_BOOK");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CaAuthor)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("CA_AUTHOR");
            entity.Property(e => e.CaCityUser)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("CA_CITY_USER");
            entity.Property(e => e.CaCover)
                .HasMaxLength(1000)
                .HasColumnName("CA_COVER");
            entity.Property(e => e.CaDescription)
                .HasMaxLength(2000)
                .HasColumnName("CA_DESCRIPTION");
            entity.Property(e => e.CaIsbn)
                .HasMaxLength(20)
                .HasColumnName("CA_ISBN");
            entity.Property(e => e.CaNameUser)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("CA_NAME_USER");
            entity.Property(e => e.CaPublisher)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("CA_PUBLISHER");
            entity.Property(e => e.CaTitle)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("CA_TITLE");
            entity.Property(e => e.CdCoverPrice)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("CD_COVER_PRICE");
            entity.Property(e => e.CdPrice)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("CD_PRICE");
            entity.Property(e => e.CdShippingPrice)
                .HasDefaultValueSql("0.00")
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("CD_SHIPPING_PRICE");
            entity.Property(e => e.DtCreation)
                .HasDefaultValueSql("GETUTCDATE()")
                .HasColumnName("DT_CREATION");
            entity.Property(e => e.DtUpdate)
                .HasDefaultValueSql("GETUTCDATE()")
                .HasColumnName("DT_UPDATE");
            entity.Property(e => e.FlActive)
                .IsRequired()
                .HasDefaultValueSql("1")
                .HasColumnName("FL_ACTIVE");
            entity.Property(e => e.FlNew)
                .IsRequired()
                .HasDefaultValueSql("1")
                .HasColumnName("FL_NEW");
            entity.Property(e => e.FlSelling).HasColumnName("FL_SELLING");
            entity.Property(e => e.FlShipping).HasColumnName("FL_SHIPPING");
            entity.Property(e => e.IdCategory).HasColumnName("ID_CATEGORY");
            entity.Property(e => e.IdCategorySub).HasColumnName("ID_CATEGORY_SUB");
            entity.Property(e => e.IdTarget)
                .HasDefaultValueSql("27")
                .HasColumnName("ID_TARGET");
            entity.Property(e => e.IdUser).HasColumnName("ID_USER");

            entity.HasOne(d => d.IdCategoryNavigation).WithMany(p => p.TBooks)
                .HasForeignKey(d => d.IdCategory)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_T_BOOK_T_CATEGORY");

            entity.HasOne(d => d.IdCategorySubNavigation).WithMany(p => p.TBooks)
                .HasForeignKey(d => d.IdCategorySub)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_T_BOOK_T_CATEGORY_SUB");

            entity.HasOne(d => d.IdTargetNavigation).WithMany(p => p.TBooks)
                .HasForeignKey(d => d.IdTarget)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_T_BOOK_T_TARGET");
        });

        modelBuilder.Entity<TCategory>(entity =>
        {
            entity.ToTable("T_CATEGORY");

            entity.HasIndex(e => e.CaName, "IX_T_CATEGORY_CA_NAME").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CaName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("CA_NAME");
        });

        modelBuilder.Entity<TCategorySub>(entity =>
        {
            entity.ToTable("T_CATEGORY_SUB");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CaDescription)
                .HasMaxLength(1000)
                .HasColumnName("CA_DESCRIPTION");
            entity.Property(e => e.CaName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("CA_NAME");
            entity.Property(e => e.IdCategory).HasColumnName("ID_CATEGORY");

            entity.HasOne(d => d.IdCategoryNavigation).WithMany(p => p.TCategorySubs)
                .HasForeignKey(d => d.IdCategory)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_T_CATEGORY_SUB_T_CATEGORY");
        });

        modelBuilder.Entity<TComunication>(entity =>
        {
            entity.ToTable("T_COMUNICATION");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CaMessage)
                .IsRequired()
                .HasMaxLength(2000)
                .HasColumnName("CA_MESSAGE");
            entity.Property(e => e.DtCreation)
                .HasDefaultValueSql("GETUTCDATE()")
                .HasColumnName("DT_CREATION");
            entity.Property(e => e.FlRead).HasColumnName("FL_READ");
            entity.Property(e => e.IdBook).HasColumnName("ID_BOOK");
            entity.Property(e => e.IdUserSender).HasColumnName("ID_USER_SENDER");

            entity.HasOne(d => d.IdBookNavigation).WithMany(p => p.TComunications)
                .HasForeignKey(d => d.IdBook)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_T_COMUNICATION_T_BOOK");
        });

        modelBuilder.Entity<TTarget>(entity =>
        {
            entity.ToTable("T_TARGET");

            entity.HasIndex(e => e.CaName, "IX_T_TARGET_CA_NAME").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CaName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("CA_NAME");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}